import type { Metadata } from "next";
import { IBM_Plex_Sans_Condensed } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Navbar from "@/components/Navbar";

const geistSans = IBM_Plex_Sans_Condensed({
  weight:"300",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params:{locale}
}: Readonly<{
  children: React.ReactNode;
  params:{locale:string}
}>) {
  return (
    <html lang={locale}>
      <body className={`  ${geistSans} flex flex-col text-white antialiased bg-[#111315] `} >
          <div className="flex flex-row  justify-between  !important">
               <div>
                   <SideBar/>
              </div>
              <div className="w-[95vw]">
                <div className="flex flex-col  justify-around gap-24 lg:gap-y-40">
                  <div>
                  <Navbar/>
                  </div>
                  <div  className=" pl-12 pr-2 lg:justify-center lg:px-10">
                    {children}
                  </div>
              </div>
              </div>
          </div>
           
           

      </body>
    </html>
  );
}
